language: node_js
sudo: required
node_js:
  - lts/*
branch: master
cache:
  directories:
    - node_modules
before_install:
 - chmod +x deploy.sh
install:
    - npm install vuepress
    - npm install vue-router@3.4.5
script:
  - ./deploy.sh