language: node_js
sudo: required
node_js:
  - 8.11.3
cache:
  directories:
    - node_modules
before_install:
 - chmod +x deploy.sh
install:
    - npm install -g vuepress
script:
  - ./deploy.sh
branch: master